=== DanielMcInnes/plugins/m-keyboard/layouts/VirtualKeyboardLayout.dtd
<!ELEMENT keyboard (layout | import)*>
<!ELEMENT import EMPTY>
<!ELEMENT layout (section+)>
<!ELEMENT section (row+)>
<!ELEMENT row (key*)>
<!ELEMENT key (binding+)>
<!ELEMENT binding EMPTY>

<!ATTLIST keyboard
  version CDATA "1.0"
  title CDATA #IMPLIED
  language CDATA #IMPLIED
  catalog CDATA #IMPLIED>

<!ATTLIST import
  file CDATA #REQUIRED>

<!ATTLIST layout
  type (general | url | email | number | phonenumber | common) "general"
  orientation (landscape | portrait) "landscape">

<!ATTLIST section
  id CDATA #REQUIRED
  movable (true | false) "true"
  type (sloppy | non-sloppy) "sloppy"
  vertical_alignment (center | full | top | bottom) #REQUIRED
  horizontal_alignment (center | full | left | right) #REQUIRED>

<!ATTLIST binding
  action (insert | shift | backspace | space | cycle | layout_menu | sym
          | return | decimal_separator | plus_minus_toggle) "insert"
  shift (true|false) "false"
  alt (true|false) "false"
  label CDATA #IMPLIED
  secondary_label CDATA #IMPLIED
  accents CDATA #IMPLIED
  accented_labels CDATA #IMPLIED
  cycleset CDATA #IMPLIED
  dead (true | false) "false">

=== DanielMcInnes/plugins/m-keyboard/layouts/hwsymbols_arabic.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM 'VirtualKeyboardLayout.dtd'>
<keyboard version="1.0" catalog="symbols">
    <layout type="general" orientation="landscape">
        <section id="symbols Sym" type="non-sloppy" movable="false" horizontal_alignment="left" vertical_alignment="center">
          <row>
            <key>
              <binding label="١"/>
              <binding shift="true" label="1"/>
            </key>
            <key>
              <binding label="٢"/>
              <binding shift="true" label="2"/>
            </key>
            <key>
              <binding label="٣"/>
              <binding shift="true" label="3"/>
            </key>
            <key>
              <binding label="٤"/>
              <binding shift="true" label="4"/>
            </key>
            <key>
              <binding label="٥"/>
              <binding shift="true" label="5"/>
            </key>
            <key>
              <binding label="٦"/>
              <binding shift="true" label="6"/>
            </key>
            <key>
              <binding label="٧"/>
              <binding shift="true" label="7"/>
            </key>
            <key>
              <binding label="٨"/>
              <binding shift="true" label="8"/>
            </key>
            <key>
              <binding label="٩"/>
              <binding shift="true" label="9"/>
            </key>
            <key>
              <binding label="٠"/>
              <binding shift="true" label="0"/>
            </key>
          </row>
          <row>
            <key>
              <binding label="⇥"/>
            </key>
            <key>
              <binding label="*"/>
            </key>
            <key>
              <binding label="#"/>
            </key>
            <key>
              <binding label="+"/>
            </key>
            <key>
              <binding label="="/>
            </key>
            <key>
              <binding label="$"/>
              <binding shift="true" label="£"/>
            </key>
            <key>
              <binding label="€"/>
              <binding shift="true" label="¥"/>
            </key>
            <key>
              <binding label="("/>
              <binding shift="true" label="["/>
            </key>
            <key>
              <binding label=")"/>
              <binding shift="true" label="]"/>
            </key>
            <key>
              <binding label="↵"/>
            </key>
          </row>
          <row>
            <key>
              <binding label="/"/>
              <binding shift="true" label="\"/>
            </key>
            <key>
              <binding label="@"/>
              <binding shift="true" label="~"/>
            </key>
            <key>
              <binding label="٪"/>
              <binding shift="true" label="‰"/>
            </key>
            <key>
              <binding label="-"/>
              <binding shift="true" label="_"/>
            </key>
            <key>
              <binding label="‘"/>
              <binding shift="true" label="&#x0022;"/>
            </key>
            <key>
              <binding label="،"/>
              <binding shift="true" label="٫"/>
            </key>
            <key>
              <binding label="؛"/>
              <binding shift="true" label="«"/>
            </key>
            <key>
              <binding label=":"/>
              <binding shift="true" label="»"/>
            </key>
            <key>
              <binding label="؟"/>
              <binding shift="true" label="?"/>
            </key>
            <key>
              <binding label="!"/>
            </key>
          </row>
        </section>
    </layout>
</keyboard>

=== DanielMcInnes/plugins/maliit-keyboard/data/languages/number.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM "VirtualKeyboardLayout.dtd">

<keyboard catalog="number" title="Number" version="1.0">
  <layout orientation="landscape" type="number">
    <section id="main" movable="false">
      <row>
        <key>
          <binding label="1" />
        </key>
        <key>
          <binding label="2" />
        </key>
        <key>
          <binding label="3" />
        </key>
        <key>
          <binding label="4" />
        </key>
        <key>
          <binding label="5" />
        </key>
        <key>
          <binding label="6" />
        </key>
        <key>
          <binding label="7" />
        </key>
        <key>
          <binding label="8" />
        </key>
        <key>
          <binding label="9" />
        </key>
        <key>
          <binding label="0" />
        </key>
      </row>
      <row>
        <spacer />
        <key width="large">
          <binding action="plus_minus_toggle" label="+/-" />
        </key>
        <key width="large">
          <binding action="decimal_separator" />
        </key>
        <key style="special" width="large">
          <binding action="backspace" label="" />
        </key>
        <key id="actionKey" style="special" width="large">
          <binding action="return" />
        </key>
      </row>
    </section>
  </layout>
  <layout orientation="portrait" type="number">
    <section id="main" movable="false">
      <row>
        <key>
          <binding label="1" />
        </key>
        <key>
          <binding label="2" />
        </key>
        <key>
          <binding label="3" />
        </key>
      </row>
      <row>
        <key>
          <binding label="4" />
        </key>
        <key>
          <binding label="5" />
        </key>
        <key>
          <binding label="6" />
        </key>
      </row>
      <row>
        <key>
          <binding label="7" />
        </key>
        <key>
          <binding label="8" />
        </key>
        <key>
          <binding label="9" />
        </key>
      </row>
      <row>
        <key>
          <binding action="plus_minus_toggle" label="+/-" />
        </key>
        <key>
          <binding label="0" />
        </key>
        <key>
          <binding action="decimal_separator" />
        </key>
      </row>
      <row>
        <key style="special" width="large">
          <binding action="backspace" label="" />
        </key>
        <spacer />
        <key id="actionKey" style="special">
          <binding action="return" />
        </key>
      </row>
    </section>
  </layout>
</keyboard>

=== DanielMcInnes/plugins/maliit-keyboard/data/languages/hy_am_alt.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM 'VirtualKeyboardLayout.dtd'>
<keyboard title="Հայերեն (հնչյունային)" version="1.0" catalog="hy" language="hy">
  <layout type="general">
    <section id="main">
      <row>
        <key>
          <binding label="ք"/>
          <binding shift="true" label="Ք"/>
        </key>
        <key>
          <binding label="ո" extended_labels="օ"/>
          <binding shift="true" label="Ո" extended_labels="Օ"/>
        </key>
		<key>
          <binding label="ե"/>
          <binding shift="true" label="Ե"/>
        </key>
        <key>
          <binding label="ռ" extended_labels="12345"/>
          <binding shift="true" label="Ռ" extended_labels="12345"/>
        </key>
        <key>
          <binding label="տ" extended_labels="67890"/>
          <binding shift="true" label="Տ" extended_labels="67890"/>
        </key>
        <key>
          <binding label="ը"/>
          <binding shift="true" label="Ը"/>
        </key>
        <key>
          <binding label="ւ" extended_labels="()"/>
          <binding shift="true" label="Ւ" extended_labels="()"/>
        </key>
        <key>
          <binding label="ի"/>
          <binding shift="true" label="Ի"/>
        </key>
        <key>
          <binding label="շ"/>
          <binding shift="true" label="Շ"/>
        </key>

		<key>
          <binding label="պ" extended_labels="փ"/>
          <binding shift="true" label="Պ" extended_labels="Փ"/>
        </key>
		<key>
          <binding label="չ" extended_labels="ճ"/>
          <binding shift="true" label="Չ" extended_labels="Ճ"/>
        </key>        
      </row>

      <row>
        <key>

          <binding label="ա"/>
          <binding shift="true" label="Ա"/>
        </key>
        <key>
          <binding label="ս"/>
          <binding shift="true" label="Ս"/>
        </key>
        <key>
          <binding label="դ"/>
          <binding shift="true" label="Դ"/>
        </key>
        <key>
          <binding label="թ"/>
          <binding shift="true" label="Թ"/>
        </key>
        <key>
          <binding label="գ"/>
          <binding shift="true" label="Գ"/>
        </key>
        <key>
          <binding label="հ"/>
          <binding shift="true" label="Հ"/>
        </key>
        <key>
          <binding label="յ"/>
          <binding shift="true" label="Յ"/>
        </key>
        <key>
          <binding label="կ"/>
          <binding shift="true" label="Կ"/>
        </key>
        <key>

          <binding label="լ"/>
          <binding shift="true" label="Լ"/>
        </key>
        <key>
          <binding label="խ"/>
          <binding shift="true" label="Խ"/>
        </key>
        <key>
          <binding label="ծ"/>
          <binding shift="true" label="Ծ"/>
        </key>
      </row>

      <row>
        <key style="special">
          <binding action="shift" label=""/>
        </key>

        <key>
          <binding label="զ"/>
          <binding shift="true" label="Զ"/>
        </key>
        <key>
          <binding label="ղ"/>
          <binding shift="true" label="Ղ"/>
        </key>
        <key>
          <binding label="ց"/>
          <binding shift="true" label="Ց"/>
        </key>
        <key>
          <binding label="վ" extended_labels="ֆ"/>
          <binding shift="true" label="Վ" extended_labels="Ֆ"/>
        </key>
        <key>
          <binding label="բ"/>
          <binding shift="true" label="Բ"/>
        </key>
        <key>
          <binding label="ն"/>
          <binding shift="true" label="Ն"/>
        </key>
        <key>
          <binding label="մ"/>
          <binding shift="true" label="Մ"/>
        </key>
        <key>
          <binding label="ձ"/>
          <binding shift="true" label="Ձ"/>
        </key>
        <key>
          <binding label="ժ"/>
          <binding shift="true" label="Ժ"/>
        </key>

        <key style="special">
          <binding action="backspace"/>
        </key>
      </row>

      <row>
        <key style="special" width="large">
          <binding action="sym" label="՞123"/>
        </key>

        <key id="emailUrlKey"><binding label="," extended_labels="՞՛–՜"/></key>
        <key>
			<binding label="ր"/>
			<binding shift="true" label="Ր"/>        
		</key>
		<key>
			<binding label="ջ"/>
			<binding shift="true" label="Ջ"/>        
		</key>

        <key width="stretched">
          <binding action="space" label=""/>
        </key>

        <key><binding label="։" extended_labels="՝․"/></key>
        <key>
          <binding label="է"/>
          <binding shift="true" label="Է"/>
        </key>
		
		<key>
          <binding label="և" extended_labels="«»"/>
          <binding shift="true" label="ություն" extended_labels="«»"/>
        </key>

        <key style="special" width="x-large" id="actionKey">
          <binding action="return"/>
        </key>
      </row>
    </section>
  </layout>

  <import file="symbols_hy.xml"/>
</keyboard>

=== DanielMcInnes/plugins/maliit-keyboard/data/languages/toolbar.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM 'VirtualKeyboardLayout.dtd'>
<keyboard title="Toolbar" version="1.0">
  <layout type="general">
    <section id="main">
      <row>
        <key><binding label="←" action="left"/></key>
        <key><binding label="→" action="right"/></key>
      </row>
    </section>
  </layout>
</keyboard>

=== DanielMcInnes/plugins/m-keyboard/layouts/fr.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM 'VirtualKeyboardLayout.dtd'>
<keyboard title="Français" version="1.0" catalog="fr" language="fr">
    <layout type="general" orientation="landscape">
        <section id="main" movable="false" vertical_alignment="center" horizontal_alignment="center">
          <row>
            <key>
              <binding accented_labels="àáâä" accents="`´^¨" label="a"/>
              <binding shift="true" accented_labels="ÀÁÂÄ" accents="`´^¨" label="A"/>
            </key>
            <key>
              <binding label="z"/>
              <binding shift="true" label="Z"/>
            </key>
            <key>
              <binding accented_labels="èéêë" accents="`´^¨" label="e"/>
              <binding shift="true" accented_labels="ÈÉÊË" accents="`´^¨" label="E"/>
            </key>
            <key>
              <binding label="r"/>
              <binding shift="true" label="R"/>
            </key>
            <key>
              <binding label="t"/>
              <binding shift="true" label="T"/>
            </key>
            <key>
              <binding accented_labels="ýÿ" accents="´¨" label="y"/>
              <binding shift="true" accented_labels="ÝŸ" accents="´¨" label="Y"/>
            </key>
            <key>
              <binding accented_labels="ùúûü" accents="`´^¨" label="u"/>
              <binding shift="true" accented_labels="ÙÚÛÜ" accents="`´^¨" label="U"/>
            </key>
            <key>
              <binding accented_labels="ìíîï" accents="`´^¨" label="i"/>
              <binding shift="true" accented_labels="ÌÍÎÏ" accents="`´^¨" label="I"/>
            </key>
            <key>
              <binding accented_labels="òóôö" accents="`´^¨" label="o"/>
              <binding shift="true" accented_labels="ÒÓÔÖ" accents="`´^¨" label="O"/>
            </key>
            <key>
              <binding label="p"/>
              <binding shift="true" label="P"/>
            </key>
            <key>
              <binding dead="true" label="¨"/>
            </key>
          </row>
          <row>
            <key>
              <binding label="q"/>
              <binding shift="true" label="Q"/>
            </key>
            <key>
              <binding label="s"/>
              <binding shift="true" label="S"/>
            </key>
            <key>
              <binding label="d"/>
              <binding shift="true" label="D"/>
            </key>
            <key>
              <binding label="f"/>
              <binding shift="true" label="F"/>
            </key>
            <key>
              <binding label="g"/>
              <binding shift="true" label="G"/>
            </key>
            <key>
              <binding label="h"/>
              <binding shift="true" label="H"/>
            </key>
            <key>
              <binding label="j"/>
              <binding shift="true" label="J"/>
            </key>
            <key>
              <binding label="k"/>
              <binding shift="true" label="K"/>
            </key>
            <key>
              <binding label="l"/>
              <binding shift="true" label="L"/>
            </key>
            <key>
              <binding label="m"/>
              <binding shift="true" label="M"/>
            </key>
            <key>
              <binding dead="true" label="^"/>
            </key>
          </row>
          <row>
            <key>
              <binding label="w"/>
              <binding shift="true" label="W"/>
            </key>
            <key>
              <binding label="x"/>
              <binding shift="true" label="X"/>
            </key>
            <key>
              <binding label="c"/>
              <binding shift="true" label="C"/>
            </key>
            <key>
              <binding label="v"/>
              <binding shift="true" label="V"/>
            </key>
            <key>
              <binding label="b"/>
              <binding shift="true" label="B"/>
            </key>
            <key>
              <binding label="n"/>
              <binding shift="true" label="N"/>
            </key>
            <key>
              <binding label="ç"/>
              <binding shift="true" label="Ç"/>
            </key>
            <key>
              <binding dead="true" label="´"/>
            </key>
            <key>
              <binding dead="true" label="`"/>
            </key>
          </row>
        </section>
        <section id="functionkey" movable="false" horizontal_alignment="left" vertical_alignment="center">
          <row>
            <key>
              <binding action="shift" label=""/>
            </key>
            <key>
              <binding action="sym" label="Sym" secondary_label="áçè"/>
              <binding shift="true" action="layout_menu" label=""/>
            </key>
            <key>
              <binding label="-"/>
              <binding shift="true" label="'"/>
            </key>
            <key>
              <binding action="space" label=""/>
              <binding shift="true" action="return" label=""/>
            </key>
            <key>
              <binding label="?"/>
              <binding shift="true" label="!"/>
            </key>
            <key>
              <binding label="."/>
              <binding shift="true" label=","/>
            </key>
            <key>
              <binding action="backspace" label=""/>
            </key>
          </row>
        </section>
    </layout>
    <layout type="general" orientation="portrait">
        <section id="functionkey" movable="false" horizontal_alignment="left" vertical_alignment="center">
          <row>
            <key>
              <binding action="shift" label=""/>
            </key>
            <key>
              <binding action="sym" label="Sym" secondary_label="áçè"/>
              <binding shift="true" action="layout_menu" label=""/>
            </key>
            <key>
              <binding action="space" label=""/>
              <binding shift="true" action="return" label=""/>
            </key>
            <key>
              <binding label="."/>
              <binding shift="true" label=","/>
            </key>
            <key>
              <binding action="backspace" label=""/>
            </key>
          </row>
        </section>
    </layout>
    <import file="symbols.xml"/>
</keyboard>

=== DanielMcInnes/plugins/m-keyboard/layouts/phonenumber_ar.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM 'VirtualKeyboardLayout.dtd'>
<keyboard version="1.0" title="Phone Number" language="phonenumber" catalog="phonenumber">
    <layout type="phonenumber" orientation="landscape">
        <section id="main" movable="false">
          <row height="x-large">
            <key>
              <binding label="&#x0661;"/>
            </key>
            <key>
              <binding label="&#x0662;"/>
            </key>
            <key>
              <binding label="&#x0663;"/>
            </key>
            <key>
              <binding label="&#x0664;"/>
            </key>
            <key>
              <binding label="&#x0665;"/>
            </key>
            <key>
              <binding label="&#x0666;"/>
            </key>
            <key>
              <binding label="&#x0667;"/>
            </key>
            <key>
              <binding label="&#x0668;"/>
            </key>
            <key>
              <binding label="&#x0669;"/>
            </key>
            <key>
              <binding label="&#x0660;"/>
            </key>
          </row>

          <row>
            <spacer/>

            <key width="xx-large">
              <binding label="&#x002A;&#x002B;" cycleset="&#x002A;&#x002B;pw" action="cycle"/>
            </key>
            <key width="xx-large">
              <binding label="&#x0023;"/>
            </key>
            <key style="special" width="xx-large">
              <binding label="" action="backspace"/>
            </key>
          </row>
        </section>
    </layout>

    <layout type="phonenumber" orientation="portrait">
        <section id="main" movable="false">
          <row>
            <key>
              <binding label="&#x0661;"/>
            </key>
            <key>
              <binding label="&#x0662;"/>
            </key>
            <key>
              <binding label="&#x0663;"/>
            </key>
          </row>

          <row>
            <key>
              <binding label="&#x0664;"/>
            </key>
            <key>
              <binding label="&#x0665;"/>
            </key>
            <key>
              <binding label="&#x0666;"/>
            </key>
          </row>

          <row>
            <key>
              <binding label="&#x0667;"/>
            </key>
            <key>
              <binding label="&#x0668;"/>
            </key>
            <key>
              <binding label="&#x0669;"/>
            </key>
          </row>

          <row>
            <key>
              <binding label="&#x002A;&#x002B;" cycleset="&#x002A;&#x002B;pw" action="cycle"/>
            </key>
            <key>
              <binding label="&#x0660;"/>
            </key>
            <key>
              <binding label="&#x0023;"/>
            </key>
          </row>

          <row>
            <spacer/>

            <key style="special" width="xx-large">
              <binding label="" action="backspace"/>
            </key>
          </row>
        </section>
    </layout>
</keyboard>

=== DanielMcInnes/plugins/maliit-keyboard/tests/language-layout-loading/languages/general_test1_symbols.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM "VirtualKeyboardLayout.dtd">

<keyboard catalog="general_test1_symbols" version="1.0">
  <layout type="general">
    <section id="symbols0" type="non-sloppy">
      <row>
        <key>
          <binding label="1" />
        </key>
      </row>
      <row>
        <key>
          <binding label="2" />
        </key>
      </row>
    </section>
    <section id="symbols1" type="non-sloppy">
      <row>
        <key>
          <binding label="3" />
        </key>
      </row>
      <row>
        <key>
          <binding label="4" />
        </key>
      </row>
    </section>
  </layout>
</keyboard>

=== DanielMcInnes/plugins/m-keyboard/layouts/hwsymbols_chinese.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM 'VirtualKeyboardLayout.dtd'>
<keyboard version="1.0" catalog="symbols">
    <layout type="general" orientation="landscape">
        <section id="symbols0" type="non-sloppy" movable="false">
          <row>
            <key>
              <binding label="1"/>
            </key>
            <key>
              <binding label="2"/>
            </key>
            <key>
              <binding label="3"/>
            </key>
            <key>
              <binding label="4"/>
            </key>
            <key>
              <binding label="5"/>
            </key>
            <key>
              <binding label="6"/>
            </key>
            <key>
              <binding label="7"/>
            </key>
            <key>
              <binding label="8"/>
            </key>
            <key>
              <binding label="9"/>
            </key>
            <key>
              <binding label="0"/>
            </key>
          </row>

          <row>
            <key>
              <binding label="⇥" action="tab"/>
            </key>
            <key>
              <binding label="*"/>
              <binding shift="true" label="'"/>
            </key>
            <key>
              <binding label="."/>
              <binding shift="true" label="#"/>
            </key>
            <key>
              <binding label="—"/>
              <binding shift="true" label="+"/>
            </key>
            <key>
              <binding label="…"/>
              <binding shift="true" label="="/>
            </key>
            <key>
              <binding label="%"/>
              <binding shift="true" label="€"/>
            </key>
            <key>
              <binding label="¥"/>
              <binding shift="true" label="$"/>
            </key>
            <key>
              <binding label="("/>
            </key>
            <key>
              <binding label=")"/>
            </key>
            <key>
              <binding label="↵" action="return"/>
            </key>
          </row>

          <row>
            <key>
              <binding label="/"/>
              <binding shift="true" label="\"/>
            </key>
            <key>
              <binding label="“"/>
              <binding shift="true" label="@"/>
            </key>
            <key>
              <binding label="”"/>
              <binding shift="true" label="~"/>
            </key>
            <key>
              <binding label="、"/>
              <binding shift="true" label="-"/>
            </key>
            <key>
              <binding label="。"/>
              <binding shift="true" label="_"/>
            </key>
            <key>
              <binding label=","/>
            </key>
            <key>
              <binding label=";"/>
            </key>
            <key>
              <binding label=":"/>
            </key>
            <key>
              <binding label="?"/>
            </key>
            <key>
              <binding label="!"/>
            </key>
          </row>
        </section>
    </layout>
</keyboard>
