=== DanielMcInnes/plugins/m-keyboard/layouts/VirtualKeyboardLayout.dtd
<!ELEMENT keyboard (layout | import)*>
<!ELEMENT import EMPTY>
<!ELEMENT layout (section+)>
<!ELEMENT section (row+)>
<!ELEMENT row (key*)>
<!ELEMENT key (binding+)>
<!ELEMENT binding EMPTY>

<!ATTLIST keyboard
  version CDATA "1.0"
  title CDATA #IMPLIED
  language CDATA #IMPLIED
  catalog CDATA #IMPLIED>

<!ATTLIST import
  file CDATA #REQUIRED>

<!ATTLIST layout
  type (general | url | email | number | phonenumber | common) "general"
  orientation (landscape | portrait) "landscape">

<!ATTLIST section
  id CDATA #REQUIRED
  movable (true | false) "true"
  type (sloppy | non-sloppy) "sloppy"
  vertical_alignment (center | full | top | bottom) #REQUIRED
  horizontal_alignment (center | full | left | right) #REQUIRED>

<!ATTLIST binding
  action (insert | shift | backspace | space | cycle | layout_menu | sym
          | return | decimal_separator | plus_minus_toggle) "insert"
  shift (true|false) "false"
  alt (true|false) "false"
  label CDATA #IMPLIED
  secondary_label CDATA #IMPLIED
  accents CDATA #IMPLIED
  accented_labels CDATA #IMPLIED
  cycleset CDATA #IMPLIED
  dead (true | false) "false">

=== DanielMcInnes/plugins/m-keyboard/layouts/pt.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM 'VirtualKeyboardLayout.dtd'>
<keyboard title="Português" version="1.0" catalog="pt" language="pt">
    <layout type="general" orientation="landscape">
        <section id="main" movable="false" vertical_alignment="center" horizontal_alignment="center">
          <row>
            <key>
              <binding label="q"/>
              <binding shift="true" label="Q"/>
            </key>
            <key>
              <binding label="w"/>
              <binding shift="true" label="W"/>
            </key>
            <key>
              <binding accented_labels="èéê" accents="`´^" label="e"/>
              <binding shift="true" accented_labels="ÈÉÊ" accents="`´^" label="E"/>
            </key>
            <key>
              <binding label="r"/>
              <binding shift="true" label="R"/>
            </key>
            <key>
              <binding label="t"/>
              <binding shift="true" label="T"/>
            </key>
            <key>
              <binding accented_labels="ý" accents="´" label="y"/>
              <binding shift="true" accented_labels="Ý" accents="´" label="Y"/>
            </key>
            <key>
              <binding accented_labels="ùúû" accents="`´^" label="u"/>
              <binding shift="true" accented_labels="ÙÚÛ" accents="`´^" label="U"/>
            </key>
            <key>
              <binding accented_labels="ìíî" accents="`´^" label="i"/>
              <binding shift="true" accented_labels="ÌÍÎ" accents="`´^" label="I"/>
            </key>
            <key>
              <binding accented_labels="òóôõ" accents="`´^~" label="o"/>
              <binding shift="true" accented_labels="ÒÓÔÕ" accents="`´^~" label="O"/>
            </key>
            <key>
              <binding label="p"/>
              <binding shift="true" label="P"/>
            </key>
            <key>
              <binding dead="true" label="^"/>
            </key>
          </row>
          <row>
            <key>
              <binding accented_labels="àáâã" accents="`´^~" label="a"/>
              <binding shift="true" accented_labels="ÀÁÂÃ" accents="`´^~" label="A"/>
            </key>
            <key>
              <binding label="s"/>
              <binding shift="true" label="S"/>
            </key>
            <key>
              <binding label="d"/>
              <binding shift="true" label="D"/>
            </key>
            <key>
              <binding label="f"/>
              <binding shift="true" label="F"/>
            </key>
            <key>
              <binding label="g"/>
              <binding shift="true" label="G"/>
            </key>
            <key>
              <binding label="h"/>
              <binding shift="true" label="H"/>
            </key>
            <key>
              <binding label="j"/>
              <binding shift="true" label="J"/>
            </key>
            <key>
              <binding label="k"/>
              <binding shift="true" label="K"/>
            </key>
            <key>
              <binding label="l"/>
              <binding shift="true" label="L"/>
            </key>
            <key>
              <binding label="ç"/>
              <binding shift="true" label="Ç"/>
            </key>
            <key>
              <binding dead="true" label="~"/>
            </key>
          </row>
          <row>
            <key>
              <binding label="z"/>
              <binding shift="true" label="Z"/>
            </key>
            <key>
              <binding label="x"/>
              <binding shift="true" label="X"/>
            </key>
            <key>
              <binding label="c"/>
              <binding shift="true" label="C"/>
            </key>
            <key>
              <binding label="v"/>
              <binding shift="true" label="V"/>
            </key>
            <key>
              <binding label="b"/>
              <binding shift="true" label="B"/>
            </key>
            <key>
              <binding label="n"/>
              <binding shift="true" label="N"/>
            </key>
            <key>
              <binding label="m"/>
              <binding shift="true" label="M"/>
            </key>
            <key>
              <binding dead="true" label="´"/>
            </key>
            <key>
              <binding dead="true" label="`"/>
            </key>
            <key>
              <binding action="backspace" label=""/>
            </key>
          </row>
        </section>
        <section id="functionkey" movable="false" horizontal_alignment="left" vertical_alignment="center">
          <row>
            <key>
              <binding action="shift" label=""/>
            </key>
            <key>
              <binding action="sym" label="Sym" secondary_label="áçè"/>
              <binding shift="true" action="layout_menu" label=""/>
            </key>
            <key>
              <binding label="-"/>
              <binding shift="true" label="‘"/>
            </key>
            <key>
              <binding action="space" label=""/>
            </key>
            <key>
              <binding label="?"/>
              <binding shift="true" label="!"/>
            </key>
            <key>
              <binding label="."/>
              <binding shift="true" label=","/>
            </key>
            <key>
              <binding action="return" label=""/>
            </key>
          </row>
        </section>
    </layout>
    <layout type="general" orientation="portrait">
        <section id="functionkey" movable="false" horizontal_alignment="left" vertical_alignment="center">
          <row>
            <key>
              <binding action="shift" label=""/>
            </key>
            <key>
              <binding action="sym" label="Sym" secondary_label="áçè"/>
              <binding shift="true" action="layout_menu" label=""/>
            </key>
            <key>
              <binding action="space" label=""/>
            </key>
            <key>
              <binding label="."/>
              <binding shift="true" label=","/>
            </key>
            <key>
              <binding action="return" label=""/>
            </key>
          </row>
        </section>
    </layout>
    <import file="symbols.xml"/>
</keyboard>

=== DanielMcInnes/plugins/maliit-keyboard/tests/language-layout-loading/languages/action_test2.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM "VirtualKeyboardLayout.dtd">

<keyboard catalog="action_test2" language="action_test2" title="ActionTest2" version="1.0">
  <layout type="general">
    <section id="main">
      <row>
        <key>
          <binding label="q"/>
        </key>
        <key>
          <binding action="shift" />
        </key>
        <key>
          <binding action="backspace" />
        </key>
        <key>
          <binding action="return" />
        </key>
      </row>
    </section>
  </layout>
</keyboard>

=== DanielMcInnes/plugins/m-keyboard/layouts/number_ar.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM 'VirtualKeyboardLayout.dtd'>
<keyboard version="1.0" title="Number" language="number" catalog="number">
    <layout type="number">
        <section id="main" movable="false" horizontal_alignment="center" vertical_alignment="center">
          <row>
            <key>
              <binding label="&#x0661;"/>
            </key>
            <key>
              <binding label="&#x0662;"/>
            </key>
            <key>
              <binding label="&#x0663;"/>
            </key>
            <key>
              <binding label="&#x0664;"/>
            </key>
            <key>
              <binding label="&#x0665;"/>
            </key>
            <key>
              <binding label="&#x0666;"/>
            </key>
            <key>
              <binding label="&#x0667;"/>
            </key>
            <key>
              <binding label="&#x0668;"/>
            </key>
            <key>
              <binding label="&#x0669;"/>
            </key>
            <key>
              <binding label="&#x0660;"/>
            </key>
          </row>
          <row>
            <spacer/>

            <key width="xx-large">
              <binding label="&#x002B;&#x002F;&#x002D;" action="plus_minus_toggle"/>
            </key>
            <key width="xx-large">
              <binding action="decimal_separator"/>
            </key>
            <key style="special" width="xx-large" rtl="true">
              <binding label="" action="backspace"/>
            </key>
          </row>
        </section>
    </layout>
</keyboard>

=== DanielMcInnes/plugins/m-keyboard/layouts/ar.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM 'VirtualKeyboardLayout.dtd'>
<keyboard version="1.0" title="الْعَرَبيّة" language="ar_SA" catalog="ar_SA">
    <layout type="general" orientation="landscape">
        <section id="main" movable="false" vertical_alignment="center" horizontal_alignment="center">
          <row>
            <key>
              <binding label="ض"/>
            </key>
            <key>
              <binding label="ص"/>
            </key>
            <key>
              <binding label="ث"/>
            </key>
            <key>
              <binding label="ق"/>
            </key>
            <key>
              <binding label="ف"/>
            </key>
            <key>
              <binding label="غ"/>
              <binding shift="true" label="إ"/>
            </key>
            <key>
              <binding label="ع"/>
            </key>
            <key>
              <binding label="ه"/>
            </key>
            <key>
              <binding label="خ"/>
            </key>
            <key>
              <binding label="ح"/>
            </key>
            <key>
              <binding label="ج"/>
            </key>
          </row>
          <row>
            <key>
              <binding label="ش"/>
            </key>
            <key>
              <binding label="س"/>
            </key>
            <key>
              <binding label="ي"/>
            </key>
            <key>
              <binding label="ب"/>
            </key>
            <key>
              <binding label="ل"/>
            </key>
            <key>
              <binding label="ا"/>
              <binding shift="true" label="أ"/>
            </key>
            <key>
              <binding label="ت"/>
            </key>
            <key>
              <binding label="ن"/>
            </key>
            <key>
              <binding label="م"/>
            </key>
            <key>
              <binding label="ك"/>
            </key>
            <key>
              <binding label="د"/>
            </key>
          </row>
          <row>
            <key>
              <binding label="ئ"/>
            </key>
            <key>
              <binding label="ء"/>
            </key>
            <key>
              <binding label="ؤ"/>
            </key>
            <key>
              <binding label="ر"/>
            </key>
            <key>
              <binding label="ى"/>
            </key>
            <key>
              <binding label="ة"/>
              <binding shift="true" label="آ"/>
            </key>
            <key>
              <binding label="و"/>
            </key>
            <key>
              <binding label="ز"/>
            </key>
            <key>
              <binding label="ظ"/>
            </key>
            <key>
              <binding label="ط"/>
            </key>
            <key>
              <binding label="ذ"/>
            </key>
          </row>
        </section>
        <section id="functionkey" movable="false" horizontal_alignment="left" vertical_alignment="center">
          <row>
            <key>
              <binding action="shift" label=""/>
            </key>
            <key>
              <binding action="sym" label="Sym" secondary_label="áçè"/>
              <binding shift="true" action="layout_menu" label=""/>
            </key>
            <key>
              <binding label="-"/>
              <binding shift="true" label="&apos;"/>
            </key>
            <key>
              <binding action="space" label=""/>
              <binding shift="true" action="return" label=""/>
            </key>
            <key>
              <binding label="؟"/>
              <binding shift="true" label="!"/>
            </key>
            <key>
              <binding label="."/>
              <binding shift="true" label=","/>
            </key>
            <key>
              <binding action="backspace" label=""/>
            </key>
          </row>
        </section>
    </layout>
    <layout type="general" orientation="portrait">
        <section id="functionkey" movable="false" horizontal_alignment="left" vertical_alignment="center">
          <row>
            <key>
              <binding action="shift" label=""/>
            </key>
            <key>
              <binding action="sym" label="Sym" secondary_label="áçè"/>
              <binding shift="true" action="layout_menu" label=""/>
            </key>
            <key>
              <binding action="space" label=""/>
              <binding shift="true" action="return" label=""/>
            </key>
            <key>
              <binding label="."/>
              <binding shift="true" label="&#x060C;"/>
            </key>
            <key>
              <binding action="backspace" label=""/>
            </key>
          </row>
        </section>
    </layout>
    <import file="symbols_ar.xml"/>
</keyboard>

=== DanielMcInnes/plugins/maliit-keyboard/tests/language-layout-loading/languages/icon_test1.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM "VirtualKeyboardLayout.dtd">

<keyboard catalog="icon_test1" language="icon_test1" title="IconTest1" version="1.0">
  <layout type="general">
    <section id="main">
      <row>
        <key>
          <binding action="backspace" />
        </key>
        <key>
          <binding action="return" />
        </key>
        <key>
          <binding action="shift" />
        </key>
        <key>
          <binding action="close" />
        </key>
      </row>
    </section>
  </layout>
</keyboard>
