=== DanielMcInnes/plugins/m-keyboard/layouts/VirtualKeyboardLayout.dtd
<!ELEMENT keyboard (layout | import)*>
<!ELEMENT import EMPTY>
<!ELEMENT layout (section+)>
<!ELEMENT section (row+)>
<!ELEMENT row (key*)>
<!ELEMENT key (binding+)>
<!ELEMENT binding EMPTY>

<!ATTLIST keyboard
  version CDATA "1.0"
  title CDATA #IMPLIED
  language CDATA #IMPLIED
  catalog CDATA #IMPLIED>

<!ATTLIST import
  file CDATA #REQUIRED>

<!ATTLIST layout
  type (general | url | email | number | phonenumber | common) "general"
  orientation (landscape | portrait) "landscape">

<!ATTLIST section
  id CDATA #REQUIRED
  movable (true | false) "true"
  type (sloppy | non-sloppy) "sloppy"
  vertical_alignment (center | full | top | bottom) #REQUIRED
  horizontal_alignment (center | full | left | right) #REQUIRED>

<!ATTLIST binding
  action (insert | shift | backspace | space | cycle | layout_menu | sym
          | return | decimal_separator | plus_minus_toggle) "insert"
  shift (true|false) "false"
  alt (true|false) "false"
  label CDATA #IMPLIED
  secondary_label CDATA #IMPLIED
  accents CDATA #IMPLIED
  accented_labels CDATA #IMPLIED
  cycleset CDATA #IMPLIED
  dead (true | false) "false">

=== DanielMcInnes/plugins/maliit-keyboard/tests/language-layout-loading/languages/icon_test2.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM "VirtualKeyboardLayout.dtd">

<keyboard catalog="icon_test2" language="icon_test2" title="IconTest2" version="1.0">
  <layout type="general">
    <section id="main">
      <row>
        <key>
          <binding label="q" />
        </key>
        <key>
          <binding label="w" icon="overriden_icon" />
        </key>
      </row>
    </section>
  </layout>
</keyboard>

=== DanielMcInnes/plugins/m-keyboard/layouts/pl.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM 'VirtualKeyboardLayout.dtd'>
<keyboard title="Polski" version="1.0" catalog="pl" language="pl">
    <layout type="general" orientation="landscape">
        <section id="main" movable="false" vertical_alignment="center" horizontal_alignment="center">
          <row>
            <key>
              <binding label="q"/>
              <binding shift="true" label="Q"/>
            </key>
            <key>
              <binding label="w"/>
              <binding shift="true" label="W"/>
            </key>
            <key>
              <binding label="e"/>
              <binding shift="true" label="E"/>
            </key>
            <key>
              <binding label="r"/>
              <binding shift="true" label="R"/>
            </key>
            <key>
              <binding label="t"/>
              <binding shift="true" label="T"/>
            </key>
            <key>
              <binding label="y"/>
              <binding shift="true" label="Y"/>
            </key>
            <key>
              <binding label="u"/>
              <binding shift="true" label="U"/>
            </key>
            <key>
              <binding label="i"/>
              <binding shift="true" label="I"/>
            </key>
            <key>
              <binding accented_labels="ó" accents="´" label="o"/>
              <binding shift="true" accented_labels="Ó" accents="´" label="O"/>
            </key>
            <key>
              <binding label="p"/>
              <binding shift="true" label="P"/>
            </key>
            <key>
              <binding label="ż"/>
              <binding shift="true" label="Ż"/>
            </key>
          </row>
          <row>
            <key>
              <binding label="a"/>
              <binding shift="true" label="A"/>
            </key>
            <key>
              <binding accented_labels="ś" accents="´" label="s"/>
              <binding shift="true" accented_labels="Ś" accents="´" label="S"/>
            </key>
            <key>
              <binding label="d"/>
              <binding shift="true" label="D"/>
            </key>
            <key>
              <binding label="f"/>
              <binding shift="true" label="F"/>
            </key>
            <key>
              <binding label="g"/>
              <binding shift="true" label="G"/>
            </key>
            <key>
              <binding label="h"/>
              <binding shift="true" label="H"/>
            </key>
            <key>
              <binding label="j"/>
              <binding shift="true" label="J"/>
            </key>
            <key>
              <binding label="k"/>
              <binding shift="true" label="K"/>
            </key>
            <key>
              <binding label="l"/>
              <binding shift="true" label="L"/>
            </key>
            <key>
              <binding label="ł"/>
              <binding shift="true" label="Ł"/>
            </key>
            <key>
              <binding dead="true" label="´"/>
            </key>
          </row>
          <row>
            <key>
              <binding accented_labels="ź" accents="´" label="z"/>
              <binding shift="true" accented_labels="Ź" accents="´" label="Z"/>
            </key>
            <key>
              <binding label="x"/>
              <binding shift="true" label="X"/>
            </key>
            <key>
              <binding accented_labels="ć" accents="´" label="c"/>
              <binding shift="true" accented_labels="Ć" accents="´" label="C"/>
            </key>
            <key>
              <binding label="v"/>
              <binding shift="true" label="V"/>
            </key>
            <key>
              <binding label="b"/>
              <binding shift="true" label="B"/>
            </key>
            <key>
              <binding accented_labels="ń" accents="´" label="n"/>
              <binding shift="true" accented_labels="Ń" accents="´" label="N"/>
            </key>
            <key>
              <binding label="m"/>
              <binding shift="true" label="M"/>
            </key>
            <key>
              <binding label="ą"/>
              <binding shift="true" label="Ą"/>
            </key>
            <key>
              <binding label="ę"/>
              <binding shift="true" label="Ę"/>
            </key>
            <key>
              <binding action="backspace" label=""/>
            </key>
          </row>
        </section>
        <section id="functionkey" movable="false" horizontal_alignment="left" vertical_alignment="center">
          <row>
            <key>
              <binding action="shift" label=""/>
            </key>
            <key>
              <binding action="sym" label="Sym" secondary_label="áçè"/>
              <binding shift="true" action="layout_menu" label=""/>
            </key>
            <key>
              <binding label="?"/>
              <binding shift="true" label="!"/>
            </key>
            <key>
              <binding action="space" label=""/>
            </key>
            <key>
              <binding label=","/>
              <binding shift="true" label="-"/>
            </key>
            <key>
              <binding label="."/>
              <binding shift="true" label=":"/>
            </key>
            <key>
              <binding action="return" label=""/>
            </key>
          </row>
        </section>
    </layout>
    <layout type="general" orientation="portrait">
        <section id="functionkey" movable="false" horizontal_alignment="left" vertical_alignment="center">
          <row>
            <key>
              <binding action="shift" label=""/>
            </key>
            <key>
              <binding action="sym" label="Sym" secondary_label="áçè"/>
              <binding shift="true" action="layout_menu" label=""/>
            </key>
            <key>
              <binding action="space" label=""/>
            </key>
            <key>
              <binding label="."/>
              <binding shift="true" label=","/>
            </key>
            <key>
              <binding action="return" label=""/>
            </key>
          </row>
        </section>
    </layout>
    <import file="symbols.xml"/>
</keyboard>

=== DanielMcInnes/plugins/maliit-keyboard/tests/language-layout-loading/languages/styling_profile_test.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM "VirtualKeyboardLayout.dtd">

<keyboard catalog="styling_profile_test" language="styling_profile_test" title="StylingProfileTest" version="1.0">
  <layout type="general">
    <section id="main" style="test">
      <row>
        <spacer/>
        <key><binding label="a"/></key>
        <key><binding label="b"/></key>
        <spacer/>
      </row>
      <row>
        <key><binding label="c"/></key>
        <spacer/>
        <key><binding label="d"/></key>
      </row>
    </section>
  </layout>
</keyboard>

=== DanielMcInnes/plugins/maliit-keyboard/tests/language-layout-loading/languages/general_test1_numbers.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM "VirtualKeyboardLayout.dtd">

<keyboard catalog="general_test1_numbers" title="GeneralTest1Numbers" version="1.0">
  <layout orientation="landscape" type="number">
    <section id="main" movable="false">
      <row>
        <key>
          <binding label="0" />
        </key>
        <key>
          <binding label="1" />
        </key>
      </row>
      <row>
        <spacer />
        <key>
          <binding label="2" />
        </key>
        <spacer />
        <key>
          <binding label="3" />
        </key>
        <spacer />
      </row>
    </section>
  </layout>
</keyboard>

=== DanielMcInnes/plugins/maliit-keyboard/tests/language-layout-loading/languages/style_test2.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM "VirtualKeyboardLayout.dtd">

<keyboard catalog="style_test2" version="1.0">
  <layout type="general">
    <section id="symbols0" type="non-sloppy" style="four_symbols">
      <row>
        <key>
          <binding label="!" />
        </key>
        <key>
          <binding label="@" />
        </key>
        <key>
          <binding label="#" />
        </key>
        <key>
          <binding label="$" />
        </key>
      </row>
    </section>
  </layout>
</keyboard>

=== DanielMcInnes/plugins/m-keyboard/layouts/fa.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM 'VirtualKeyboardLayout.dtd'>
<keyboard version="1.0" title="فارسى" language="fa" catalog="virtual-keyboard" autocapitalization="false">
  <layout type="general">
    <section id="main" style="bigfont">
      <row>
        <key>
          <binding label="ض"/>
        </key>
        <key>
          <binding label="ص"/>
        </key>
        <key>
          <binding label="ث"/>
        </key>
        <key>
          <binding label="ق"/>
        </key>
        <key>
          <binding label="ف"/>
        </key>
        <key>
          <binding label="غ"/>
        </key>
        <key>
          <binding label="ع"/>
        </key>
        <key>
          <binding label="ه"/>
        </key>
        <key>
          <binding label="ح"/>
          <binding shift="true" label="خ"/>          
        </key>
        <key>
          <binding label="ج"/>
          <binding shift="true" label="چ"/>
        </key>
      </row>

      <row>
        <key>
          <binding label="ش"/>
        </key>
        <key>
          <binding label="س"/>
        </key>
        <key>
          <binding label="ی"/>
        </key>
        <key>
          <binding label="ب"/>
        </key>
        <key>
          <binding label="ل"/>
          <binding shift="true" label="ۀ"/>
        </key>
        <key>
          <binding label="ا"/>
          <binding shift="true" label="آ"/>
        </key>
        <key>
          <binding label="ت"/>
        </key>
        <key>
          <binding label="ن"/>
        </key>
        <key>
          <binding label="م"/>
          <binding shift="true" label="پ"/>
        </key>
        <key>
          <binding label="ک"/>
          <binding shift="true" label="گ"/>          
        </key>
      </row>
	
      <row>
        <key style="special" width="x-large">
          <binding action="shift"/>
        </key>

        <key>
          <binding label="ظ"/>
          <binding shift="true" label="ة"/>
        </key>
        <key>
          <binding label="ط"/>
          <binding shift="true" label="ي"/>
        </key>
        <key>
          <binding label="ز"/>
          <binding shift="true" label="ژ"/>
        </key>
        <key>
          <binding label="ر"/>
          <binding shift="true" label="ؤ"/>
        </key>
        <key>
          <binding label="ذ"/>
          <binding shift="true" label="إ"/>
        </key>
        <key>
          <binding label="د"/>
          <binding shift="true" label="أ"/>
        </key>
        <key>
          <binding label="ئ"/>
          <binding shift="true" label="ء"/>
        </key>

        <key style="special"  width="x-large">
          <binding action="backspace"/>
        </key>
      </row>

      <row>
        <key style="special" width="x-large">
          <binding action="sym" label="؟٣٢١"/>
        </key>
        
        <key id="emailUrlKey"><binding label="،"/></key>
        <key><binding label="."/></key>

        <key width="stretched">
          <binding action="space"/>
        </key>
        
        <key>
          <binding label="و"/>
        </key>

        <key style="special" width="xx-large" id="actionKey">
          <binding action="return"/>
        </key>
      </row>
    </section>
  </layout>

  <import file="symbols_fa.xml"/>
</keyboard>

=== DanielMcInnes/plugins/m-keyboard/layouts/symbols_fa.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM 'VirtualKeyboardLayout.dtd'>
<keyboard version="1.0" catalog="symbols">
  <layout type="general">
    <section id="symbols0" type="non-sloppy">
      <row>
        <key>
          <binding label="&#x06F1;"/>
        </key>
        <key>
          <binding label="&#x06F2;"/>
        </key>
        <key>
          <binding label="&#x06F3;"/>
        </key>
        <key>
          <binding label="&#x06F4;"/>
        </key>
        <key>
          <binding label="&#x06F5;"/>
        </key>
        <key>
          <binding label="&#x06F6;"/>
        </key>
        <key>
          <binding label="&#x06F7;"/>
        </key>
        <key>
          <binding label="&#x06F8;"/>
        </key>
        <key>
          <binding label="&#x06F9;"/>
        </key>
        <key>
          <binding label="&#x06F0;"/>
        </key>
      </row>

      <row>
        <key>
          <binding label="*"/>
        </key>
        <key>
          <binding label="#"/>
        </key>
        <key>
          <binding label="+"/>
        </key>
        <key>
          <binding label="-"/>
        </key>
        <key>
          <binding label="_"/>
        </key>
        <key>
          <binding label="="/>
        </key>
        <key>
          <binding label="٪"/>
        </key>
        <key>
          <binding label="&#x0026;"/>
        </key>
        <key>
          <binding label="("/>
        </key>
        <key>
          <binding label=")"/>
        </key>
      </row>

      <row>
        <key style="special">
          <binding action="switch" label="1/2"/>
        </key>
        <key>
          <binding label="@" quickpick="true"/>
        </key>
        <key>
          <binding label="~"/>
        </key>
        <key>
          <binding label="/"/>
        </key>
        <key>
          <binding label="\"/>
        </key>
        <key>
          <binding label="&#x0027;" quickpick="true"/>
        </key>
        <key>
          <binding label="&#x066B;"/>
        </key>
        <key>
          <binding label="!"/>
        </key>
        <key>
          <binding label="&#x061F;"/>
        </key>
        
        <key style="special">
          <binding action="backspace"/>
        </key>
      </row>

      <row>
        <key style="special" width="large">
          <binding action="sym" label="&#x0627;&#x200C;&#x0628;&#x200C;&#x062A;"/>
        </key>
        
        <key><binding label="&#x060C;"/></key>
        <key><binding label="."/></key>
        
        <key width="stretched">
          <binding action="space"/>
        </key>
        
        <key><binding label="&#x061B;"/></key>
        
        <key style="special" width="xx-large" id="actionKey">
          <binding action="return"/>
        </key>

      </row>
    </section>

    <section id="symbols1" type="non-sloppy">
      <row>
        <key>
          <binding label="1"/>
        </key>
        <key>
          <binding label="2"/>
        </key>
        <key>
          <binding label="3"/>
        </key>
        <key>
          <binding label="4"/>
        </key>
        <key>
          <binding label="5"/>
        </key>
        <key>
          <binding label="6"/>
        </key>
        <key>
          <binding label="7"/>
        </key>
        <key>
          <binding label="8"/>
        </key>
        <key>
          <binding label="9"/>
        </key>
        <key>
          <binding label="0"/>
        </key>
      </row>

      <row>
        <key>
          <binding label="€"/>
        </key>
        <key>
          <binding label="£"/>
        </key>
        <key>
          <binding label="$"/>
        </key>
        <key>
          <binding label="¥"/>
        </key>
        <key>
          <binding label="﷼"/>
        </key>
        <key>
          <binding label="§"/>
        </key>
        <key>
          <binding label="%"/>
        </key>
        <key>
          <binding label="‰"/>
        </key>
        <key>
          <binding label="["/>
        </key>
        <key>
          <binding label="]"/>
        </key>
      </row>

      <row>
        <key style="special">
          <binding action="switch" label="2/2"/>
        </key>
        <key>
          <binding label="&lt;"/>
        </key>
        <key>
          <binding label="&gt;"/>
        </key>
        <key>
          <binding label="«"/>
        </key>
        <key>
          <binding label="»"/>
        </key>
        <key>
          <binding label="&#x0022;"/>
        </key>
        <key>
          <binding label="“"/>
        </key>
        <key>
          <binding label="”"/>
        </key>
        <key>
          <binding label="?"/>
        </key>

        <key style="special">
          <binding action="backspace"/>
        </key>
      </row>

      <row>
        <key style="special" width="large">
          <binding action="sym" label="&#x0627;&#x200C;&#x0628;&#x200C;&#x062A;"/>
        </key>
        
        <key><binding label=";"/></key>
        <key><binding label="."/></key>
        
        <key width="stretched">
          <binding action="space"/>
        </key>
		
        <key><binding label=":"/></key>
        
        <key style="special" width="xx-large" id="actionKey">
          <binding action="return"/>
        </key>
      </row>
    </section>
  </layout>
</keyboard>

=== DanielMcInnes/plugins/m-keyboard/layouts/phonenumber.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM 'VirtualKeyboardLayout.dtd'>
<keyboard version="1.0" title="Phone Number" language="phonenumber" catalog="phonenumber">
    <layout type="phonenumber" orientation="landscape">
        <section id="main" movable="false" horizontal_alignment="center" vertical_alignment="center">
          <row>
            <key>
              <binding label="1"/>
            </key>
            <key>
              <binding label="2" secondary_label="abc"/>
            </key>
            <key>
              <binding label="3" secondary_label="def"/>
            </key>
            <key>
              <binding label="4" secondary_label="ghi"/>
            </key>
            <key>
              <binding label="5" secondary_label="jkl"/>
            </key>
            <key>
              <binding label="6" secondary_label="mno"/>
            </key>
            <key>
              <binding label="7" secondary_label="pqrs"/>
            </key>
            <key>
              <binding label="8" secondary_label="tuv"/>
            </key>
            <key>
              <binding label="9" secondary_label="wxyz"/>
            </key>
            <key>
              <binding label="0"/>
            </key>
          </row>
        </section>
        <section id="functionkey" movable="false" horizontal_alignment="right" vertical_alignment="center">
          <row>
            <key>
              <binding label="&#x002A;&#x002B;" cycleset="&#x002A;&#x002B;pw" action="cycle"/>
            </key>
            <key>
              <binding label="&#x0023;"/>
            </key>
            <key>
              <binding label="" action="backspace"/>
            </key>
          </row>
        </section>
    </layout>
    <layout type="phonenumber" orientation="portrait">
        <section id="main" movable="false" horizontal_alignment="center" vertical_alignment="center">
          <row>
            <key>
              <binding label="1"/>
            </key>
            <key>
              <binding label="2" secondary_label="abc"/>
            </key>
            <key>
              <binding label="3" secondary_label="def"/>
            </key>
          </row>
          <row>
            <key>
              <binding label="4" secondary_label="ghi"/>
            </key>
            <key>
              <binding label="5" secondary_label="jkl"/>
            </key>
            <key>
              <binding label="6" secondary_label="mno"/>
            </key>
          </row>
          <row>
            <key>
              <binding label="7" secondary_label="pqrs"/>
            </key>
            <key>
              <binding label="8" secondary_label="tuv"/>
            </key>
            <key>
              <binding label="9" secondary_label="wxyz"/>
            </key>
          </row>
          <row>
            <key>
              <binding label="&#x002A;&#x002B;" cycleset="&#x002A;&#x002B;pw" action="cycle"/>
            </key>
            <key>
              <binding label="0"/>
            </key>
            <key>
              <binding label="&#x0023;"/>
            </key>
          </row>
        </section>
        <section id="functionkey" movable="false" horizontal_alignment="right" vertical_alignment="center">
          <row>
            <key>
              <binding label="" action="backspace"/>
            </key>
          </row>
        </section>
    </layout>
</keyboard>
